CL_SITES_URL = "https://www.craigslist.org/about/sites"

CL_SITE_IGNORED_SUBDOMAINS = ['forums', 'www', 'blog']

CL_NOMINATIM_AGENT = "DealifyCraigslist"

CL_QUERY_SLEEP_INTERVAL_SECONDS_MIN = 5
CL_QUERY_SLEEP_INTERVAL_SECONDS_MAX = 20
CL_QUERY_MAX_RETRIES = 10
CL_QUERY_MAX_QUERIES = 250
CL_QUERY_RATE_LIMIT_SLEEP_INTERVAL_SECONDS = 60

CL_OLD_ITEMS_SLEEP_INTERVAL_SECONDS_MIN = 5
CL_OLD_ITEMS_SLEEP_INTERVAL_SECONDS_MAX = 20
CL_OLD_ITEMS_MAX_RETRIES = 10
CL_OLD_ITEMS_MAX_ITEMS = 250
CL_OLD_ITEMS_RATE_LIMIT_SLEEP_INTERVAL_SECONDS = 60
CL_OLD_ITEMS_INTERVAL_DAYS = 2
